"""empty message

Revision ID: 39b7d8293994
Revises: f14dacf699a9
Create Date: 2022-08-18 15:03:52.842580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b7d8293994'
down_revision = 'f14dacf699a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uid_md5', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['uid_md5'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'uid_md5')
    # ### end Alembic commands ###
