"""empty message

Revision ID: 46735a4df9e7
Revises: 7294ccc246cf
Create Date: 2022-08-17 15:59:46.080746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46735a4df9e7'
down_revision = '7294ccc246cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_captcha', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('user', 'uid',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'join_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('userexts', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userexts', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user', 'join_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'uid',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('email_captcha', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
