"""empty message

Revision ID: 4dd52db15c65
Revises: 92c368eadf34
Create Date: 2022-08-19 19:31:30.335122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dd52db15c65'
down_revision = '92c368eadf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('aid_md5', sa.String(length=255), nullable=True))
    op.drop_index('ix_article_uid_md5', table_name='article')
    op.create_index(op.f('ix_article_aid_md5'), 'article', ['aid_md5'], unique=True)
    op.drop_column('article', 'uid_md5')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('uid_md5', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_article_aid_md5'), table_name='article')
    op.create_index('ix_article_uid_md5', 'article', ['uid_md5'], unique=False)
    op.drop_column('article', 'aid_md5')
    # ### end Alembic commands ###
