"""empty message

Revision ID: 506d0d067c61
Revises: 93276358d306
Create Date: 2022-08-20 09:57:58.513361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506d0d067c61'
down_revision = '93276358d306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('notlikes', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.cid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    op.add_column('article', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('notlikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'notlikes')
    op.drop_column('comment', 'likes')
    op.drop_column('article', 'likes')
    op.drop_table('reply')
    # ### end Alembic commands ###
