"""empty message

Revision ID: 6cadf7b000d2
Revises: 39b7d8293994
Create Date: 2022-08-19 13:34:45.182713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cadf7b000d2'
down_revision = '39b7d8293994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tagname', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_index(op.f('ix_tag_tagname'), 'tag', ['tagname'], unique=True)
    op.create_table('article',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('draft', sa.Boolean(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('ar_t',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_tid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.aid'], ),
    sa.ForeignKeyConstraint(['tag_tid'], ['tag.tid'], )
    )
    op.create_table('comment',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.aid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('sort',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sortname', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.aid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_sort_sortname'), 'sort', ['sortname'], unique=True)
    op.drop_index('uid_md5', table_name='user')
    op.create_index(op.f('ix_user_uid_md5'), 'user', ['uid_md5'], unique=True)
    op.add_column('userexts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('userexts_ibfk_1', 'userexts', type_='foreignkey')
    op.create_foreign_key(None, 'userexts', 'user', ['user_id'], ['uid'])
    op.drop_column('userexts', 'user_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userexts', sa.Column('user_uid', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'userexts', type_='foreignkey')
    op.create_foreign_key('userexts_ibfk_1', 'userexts', 'user', ['user_uid'], ['uid'])
    op.drop_column('userexts', 'user_id')
    op.drop_index(op.f('ix_user_uid_md5'), table_name='user')
    op.create_index('uid_md5', 'user', ['uid_md5'], unique=False)
    op.drop_index(op.f('ix_sort_sortname'), table_name='sort')
    op.drop_table('sort')
    op.drop_table('comment')
    op.drop_table('ar_t')
    op.drop_table('article')
    op.drop_index(op.f('ix_tag_tagname'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
