"""empty message

Revision ID: 71efd28d772e
Revises: 8e1d31228c92
Create Date: 2022-08-19 15:17:33.527060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71efd28d772e'
down_revision = '8e1d31228c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('navname', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_index(op.f('ix_nav_navname'), 'nav', ['navname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nav_navname'), table_name='nav')
    op.drop_table('nav')
    # ### end Alembic commands ###
