"""empty message

Revision ID: 8e1d31228c92
Revises: 6cadf7b000d2
Create Date: 2022-08-19 15:13:01.129401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1d31228c92'
down_revision = '6cadf7b000d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoucang',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.aid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], )
    )
    op.add_column('user', sa.Column('ban', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ban')
    op.drop_table('shoucang')
    # ### end Alembic commands ###
