"""empty message

Revision ID: 92c368eadf34
Revises: 71efd28d772e
Create Date: 2022-08-19 19:27:49.128768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c368eadf34'
down_revision = '71efd28d772e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('uid_md5', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_article_uid_md5'), 'article', ['uid_md5'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_uid_md5'), table_name='article')
    op.drop_column('article', 'uid_md5')
    # ### end Alembic commands ###
