"""empty message

Revision ID: 97792aeca523
Revises: beddbc3c740c
Create Date: 2022-08-23 19:15:03.415727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97792aeca523'
down_revision = 'beddbc3c740c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_like',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like')
    # ### end Alembic commands ###
