"""empty message

Revision ID: f14dacf699a9
Revises: 2e3c1d4c9087
Create Date: 2022-08-17 16:21:17.803199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f14dacf699a9'
down_revision = '2e3c1d4c9087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_captcha', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_captcha', 'phone',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('email_captcha', 'captcha',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_captcha', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_captcha', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('email_captcha', 'captcha',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_captcha', 'phone',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('email_captcha', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
